Update test workflow

diff --git a/.github/workflows/stm32build.yml b/.github/workflows/stm32build.yml
--- a/.github/workflows/stm32build.yml
+++ b/.github/workflows/stm32build.yml
@@ -20,9 +20,18 @@ jobs:
         cd "STM32/UnitTesting"
         cmake CMakeLists.txt
         make
-        output=$(./CA_UnitTesting)
-        echo $output
-        if [[ $output =~ "failed" ]]; then 
-          echo "Test failed"
-          exit 1
-        fi
+        # Extract the values assigned to the TARGET_NAMES variable
+        TARGET_NAMES=$(awk '/set\(TARGET_NAMES/{flag=1; next} /\)/{flag=0} flag' CMakeLists.txt)
+
+        # Remove leading and trailing whitespace from the values
+        TARGET_NAMES=$(echo "$TARGET_NAMES" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
+
+        # Loop over the TARGET_NAMES and echo each line
+        while IFS= read -r target_name; do
+          output=$(./$target_name)
+          echo $output
+          if [[ $output =~ "failed" ]]; then 
+            echo "Test failed"
+            exit 1
+          fi
+        done <<< "$TARGET_NAMES"
